<?php
/**
 * trm_menu_schedule data
 * jf
 * 31.05.17
 */
?>

<?php $editor_id = 'tmce';?>
<form onsubmit="return submit_form(this)" method="post" data-tmce-id="#<?php echo $editor_id;?>">
    <label for="title">Titel</label> <input type="text" id="title" name="title">
    <?php

        $content = isset($_POST['editor']) ? $_POST['editor'] : '<h1>Test</h1>';
        $settings = array(
            'media_buttons' => false,
            'quicktags'     => array("buttons"=>"link,img,close"),
            'textarea_name' => "editor",
            'tinymce'       => array(
                //'toolbar1' => 'bold, italic, underline,|,fontsizeselect',
                'toolbar2'=>false
            ),
            'editor_height' => 100
        );
        wp_editor( $content, $editor_id ,$settings);

    ?>
    <input type="submit">
    <?php  _WP_Editors::editor_js();?>

</form>
