<?php
/**
 * trm_menu_schedule right column
 * jf
 * 31.05.17
 *
 * tinymce settings sample:
 *  array(
        'media_buttons' => false,
        'teeny' => true,
        'tinymce'       => array(
            'toolbar1' => 'italic, underline,|,fontsizeselect',
        ),
        'editor_height' => 200
    );
 * https://make.wordpress.org/core/2017/05/23/addition-of-tinymce-to-the-text-widget/
 * https://make.wordpress.org/core/2017/05/20/editor-api-changes-in-4-8/
 */
?>

<?php
    $data = $this->selectData();
?>
<label for="title">Titel</label> <input type="text" id="title" name="title" value="<?php echo $data['title'];?>">
<label for="date">Datum</label> <input type="text" id="date" readonly name="date" value="<?php echo $data['date']?>">
<textarea id="editor_1" name="editor_1" style="height:200px;"><?php echo $data['content'];?></textarea>

<input type="submit" id="menu-schedule-form-submit">
