<?php
/**
 * trm_menu_schedule right column
 * jf
 * 31.05.17
 *
 * tinymce settings sample:
 *  array(
        'media_buttons' => false,
        'teeny' => true,
        'tinymce'       => array(
            'toolbar1' => 'italic, underline,|,fontsizeselect',
        ),
        'editor_height' => 200
    );
 */
?>

<?php
    $data = $this->selectData();
?>
<label for="title">Titel</label> <input type="text" id="title" name="title" value="<?php echo $data['title'];?>">
<label for="date">Datum</label> <input type="text" id="date" readonly name="date" value="<?php echo $data['date']?>">
<textarea id="editor_1" name="editor_1"><?php echo $data['content'];?></textarea>

<input type="submit" id="menu-schedule-form-submit">
