<?php
/**
 * trm_menu_schedule left column
 * jf
 * 01.06.17
 */
?>
<h2>Speiseplan </h2>
<p>Datum wählen ...</p>
<input id="datepicker" name="datepicker" type="hidden" value="<?php echo $this->datepicker;?>">
<div id="datepicker-control"></div>
<button id="load-form-button" style="display:none;">load</button>

<h1>Wochenmenü - aktuelle Woche</h1>
<?php echo $this->getWeekMenu();?>

<h1>Wochenmenü - nächste Woche</h1>
<?php echo $this->getNextWeekMenu();?>
