<?php
/**
 * trm_menu_schedule main
 * jf
 * 31.05.17
 */
$this->insertUpdateData();
$data = $this->selectData();

?>
<div class="wrap">
    <div class="row wp-clearfix">
        <form id="menu-schedule-form" action="<?php echo $this->permalink;?>" method="post">
            <div id="col-left">
                <?php require_once PLUGIN_DIR_PATH.'trm/trm_menu_schedule/phtml/admin/col-left.phtml';?>
            </div>
            <div id="col-right">
                <?php
                    if($this->action){
                        include PLUGIN_DIR_PATH.'trm/trm_menu_schedule/phtml/admin/col-right.phtml';
                    }
                ?>

            </div>
        </form>
    </div>
</div>
