<?php
/**
 * trm_menu_schedule weekly menu
 * jf
 * 01.06.17
 */
?>

<table class="admin-weekmenu">
    <?php foreach($this->weekmenu as $menu):$date = $this->germanDate($menu['date']);?>
        <tr>
            <td><a href="<?php echo $this->permalink.'&datepicker='.$date;?>">
                    <?php echo $this->weekday($date);?>,
                    <?php echo $date;?>
                </a>
            </td>
            <td><?php echo $menu['title'];?></td>
            <td><?php echo $menu['content'];?></td>
        </tr>
    <?php endforeach;?>
</table>
