<?php
	$i = 0;
	$class = $settings['showthumbs'] == 1 ? 'hidethumbs' : 'showthumbs';
	$gallery_style = !empty($settings['gallery-style']) ? ' style="'.$settings['gallery-style'].'"' : '';
	$item_style = !empty($settings['item-style']) ? ' style="'.$settings['item-style'].'"' : '';
?>
<!--
<div class="gallery-options"></div>
-->
<div class="gallery-title"><?php echo $this->getTitle();?></div>
<div class="gallery-description"><?php echo $this->getDescription();?></div>
<div class="gallery <?php echo $class;?>"<?php echo $gallery_style;?> data-image-sizes="<?php echo htmlentities(json_encode($image_sizes),ENT_QUOTES, 'UTF-8')?>">
	<?php foreach ($image_list as $entry):?>
		<figure class="gallery-item item-<?php echo $i++;?>"<?php echo $item_style;?>>
			<div class="gallery-icon landscape">
				<?php echo $entry;?>
			</div>
		</figure>
	<?php endforeach;?>
</div>
