<div class="jumbotron  jumbotron--with-captions">
	<div class="carousel  slide  fade" id="headerCarousel" data-ride="carousel" data-interval="5000">
		<div class="carousel-inner">
			<?php foreach ($images as $key => $val) : ?>
				<div class="item <?php echo ($key == 0) ? ' active' : ''; ?>">

					<?php echo wp_get_attachment_image( $val['image']['id'], 'full', false);?>
					<?php if($val['title'] || $val['text']):?>
						<div class="jumbotron-content">
							<h1 class="jumbotron-content__title"><?php echo $val['title'];?></h1>
							<div class="jumbotron-content__description">
								<?php echo $val['text'];?>
							</div>
						</div>
					<?php endif;?>
				</div>

			<?php endforeach; ?>
		</div>
		<a class="left  jumbotron__control" href="#headerCarousel" role="button" data-slide="prev"> <i class="fa  fa-chevron-left"></i> </a>
		<a class="right  jumbotron__control" href="#headerCarousel" role="button" data-slide="next"> <i class="fa  fa-chevron-right"></i> </a>
	</div>
</div>
